### ISSUE TITLE
input:disabled doesn't respect disabled parent fieldset

### ISSUE THREAD

**Issue by dmethvin** [jquery/sizzle#174]
While working on http://bugs.jquery.com/ticket/12134 I was surprised to see that this does work in `qSA`: http://jsfiddle.net/dmethvin/65QUz/

**Comment by phazei** [comment]
Will sizzle 2.3 be included in jQuery 2.x?  I just noticed that jQ3.x is on it's way.  If I install sizzle 2.3 on its own, will jQ use it?

**Comment by gibson042** [comment]
The team opted not to include Sizzle 2.3 in jQuery 2.x, but you can get this particular improvement by loading Sizzle yourself and copying over the pseudos:
```js
jQuery.expr.pseudos.enabled = Sizzle.selectors.pseudos.enabled;
jQuery.expr.pseudos.disabled = Sizzle.selectors.pseudos.disabled;
```
