### ISSUE TITLE
"unsupported pseudo: regex" error in Firefox and IE9/10

### ISSUE THREAD

**Issue by neave** [jquery/sizzle#216]
A popular website I own has been reporting this Sizzle error (via jQuery) for many users running Firefox (21/22) and IE (9/10):

`Syntax error, unrecognized expression: unsupported pseudo: regex`

This is using the jQuery 1.10, all minor revisions 1.10.0, 1.10.1 and 1.10.2. It does not affect Chrome, Safari or Opera, only Firefox and IE 9 and 10. Unfortunately I cannot reproduce the problem myself, but it does occur regularly and consistently. This error did not occur in any version before jQuery 1.10.

The error is thrown at this point:

`fn = Expr.pseudos[ pseudo ] || Expr.setFilters[ pseudo.toLowerCase() ] ||
                    Sizzle.error( "unsupported pseudo: " + pseudo );`

Does anyone know why this would affect only Firefox and IE 9 and 10?

**Comment by michael7213** [comment]
hi paul my name ic michael
