### ISSUE TITLE
Isolate locally-built sizzle files from released code

### ISSUE THREAD

**Issue by gibson042** [jquery/sizzle#239]
Since `dist/sizzle*` are included in the repo, every `grunt` tends to force the working directory into a dirty state, disrupting size comparison and making pull requests less straightforward. We should update the build, testing, and/or release processes to isolate locally-built output from tagged releases, either through separate "build" and "dist" locations or through special release commits that diverge from the master branch.

**Comment by mgol** [comment]
PR: #467
