### ISSUE TITLE
Selecting elements by empty attribute in a context other than document fails

### ISSUE THREAD

**Issue by tiff** [jquery/sizzle#24]
Dear Sizzle Devs,

While working with Sizzle I found a minor but annoying issue.

I have a dom tree that looks like this:

```
<div id="foo">
  <span data-foo></span>
</div>
```

Now when I execute this:
    Sizzle("[data-foo]").length;

I get 1, which is obviously correct, but when I provide a context:
    Sizzle("[data-foo]", document.getElementById("foo")).length;

It returns 0, which is wrong.

Some more information:
-   It also happens when the attribute has an empty string as value ([data-foo=""])
-   It also happens when I provide a tag name in front of the selector (span[data-foo])
-   It also happens with other empty attributes like "readonly"

Here's a demo of the problem (including tests with native querySelectorAll):
http://tifftiff.de/sizzle_bug/

The problem exists in my Chrome 6, Safari 5, IE 8 and Firefox 3.6/4.0b.
In IE 6+7 both tests return 0 regardless of the given context.

**Comment by RiZKiT** [comment]
In jQuery 3.3.1 this bug seems to be there again, but I don't know when it was reintroduced. 

Maybe someone else can validate this, if it's really the case, I can open a new issue.

**Comment by mgol** [comment]
This is a really old issue. If you experience it again and can reproduce in a small test case, please open a new issue.
