### ISSUE TITLE
Pseudo argument unquoted fallback yields strange behavior

### ISSUE THREAD

**Issue by gibson042** [jquery/sizzle#264]
cc @timmywil

Spun off from #261.

Our current pseudo argument parser prefers quotes, but will fall back on greedy consumption up to the last closing parenthesis if they are not found or incorrect. We should decide on explicit behavior.

| Selector | Liberal Fallback (current) |
| --- | --- |
| unclosed: `:contains(...` | _Syntax Error_ |
| no quotes: `:contains(Too Ra Loo Ra Loo Ral)` | `Too Ra Loo Ra Loo Ral` |
| parentheses: `:contains(:-))` | `:-)` |
| properly quoted: `:contains('\'sup?')` | `'sup?` |
| leading quote: `:contains("foo" is bar)` | `"foo" is bar` |
| leading quote: `:contains("unterminated)` | `"unterminated` |
| trailing quote: `:contains(Quoth the raven, 'Nevermore.')` | `Quoth the raven, 'Nevermore.'` |
| trailing quote: `:contains(unopened')` | `unopened'` |
| embedded quote: `:contains(It's a bird, it's a plane)` | `It's a bird, it's a plane` |

Other options to come later; I just wanted to document a wide swath of cases. Note also that our current aggressiveness can cause problems with _subsequent_ selector components (e.g., we accept `:contains("unterminated):not(:contains("Terminator"))` as valid, and matching only elements containing `"unterminated):not(:contains("Terminator")`).

**Comment by mgol** [comment]
@timmywil @gibson042 are there any changes here that you'd eventually want to apply to jQuery or are we fine to close this issue?

**Comment by timmywil** [comment]
We'll use "Unsupported selector" (discussed in the [Sizzle issue](https://github.com/jquery/sizzle/issues/326)) for tokenize failures when we get to the selector rewrite.

**Comment by mgol** [comment]
Closing as discussed during the last team meeting
