### ISSUE TITLE
Automate updating AUTHORS.txt before release

### ISSUE THREAD

**Issue by mgol** [jquery/sizzle#308]
Our [AUTHORS.txt](https://github.com/jquery/sizzle/blob/master/AUTHORS.txt) file is terribly outdated, even @markelog isn't on the list. We should automate populating it, at least before releases.

**Comment by markelog** [comment]
I wonder if need this file, isn't https://github.com/jquery/sizzle/graphs/contributors enough?

**Comment by arthurvr** [comment]
Personally I don't think this is needed too, but if it is included it must be up-to-date.

**Comment by mzgol** [comment]
> I wonder if need this file, isn't https://github.com/jquery/sizzle/graphs/contributors enough?

This concerns other repos as well, so summoning @jquery/core @scottgonzalez @arschmitz.

**Comment by scottgonzalez** [comment]
Here's what we do for jQuery UI: https://github.com/jquery/jquery-ui/blob/c89cb74893c4f99d6163e29110c36d9e02dc7df1/Gruntfile.js#L338

You don't need the author mapping to hide email addresses in Sizzle, so the implementation is a bit simpler. You probably also don't have any prior authors (I assume the git history is complete).

**Comment by arthurvr** [comment]
Feel free to assign this to me. PR incoming.

**Comment by markelog** [comment]
@arthurvr there is no rush, let's decide how we can handle this.

@scottgonzalez 

https://github.com/jquery/jquery-ui/blob/c89cb74893c4f99d6163e29110c36d9e02dc7df1/Gruntfile.js#L351 :-)

Sounds like this task could be used in couple of projects, how about we moved it to the separate repo and publish it?

btw, so you think we need this file? Could clarify?

**Comment by arschmitz** [comment]
@markelog it is its own repo and published and already used in several other repos. https://github.com/scottgonzalez/grunt-git-authors. It's already used in many other repos including Core, UI, Mobile, and Chassis.

**Comment by arschmitz** [comment]
Also the contributor graph is not enough it does not list all contributors. For example because he removed the email he used to make the commits from his github account Scott Jehl does not show on the mobile graph even though he's the first contributor and one of the top all time contributors.

**Comment by markelog** [comment]
@arthurvr good to know, thanks for the info.

**Comment by mzgol** [comment]
@arschmitz 
> For example because he removed the email he used to make the commits from his github account Scott Jehl does not show on the mobile graph even though he's the first contributor and one of the top all time contributors

This seems like one of those things that should be handled via Git .mailmap. Doesn't that work?

**Comment by arschmitz** [comment]
@mzgol thats a bit easier said then done you would first have to know they were missing in the first place. This case was obvious him being a former team member others with only a single commit would be nearly impossible to find.

**Comment by mzgol** [comment]
@arschmitz 
> @mzgol thats a bit easier said then done you would first have to know they were missing in the first place

Sure; I was just surprised about this specific case of the original Mobile author.

> Also i do not know if github takes into account the .mailmap for their graphs or not i would think they did but never tried.

It does work and I'd be very surprised if it didn't. It's not something GitHub can decide not to take into account; Git itself supports .mailmap pretty deeply so any commands regarding commit authors take that into account automatically.

**Comment by scottgonzalez** [comment]
The key factor is that GitHub graphs only show GitHub users, and that's never guaranteed to be a complete list.

**Comment by mzgol** [comment]
> The key factor is that GitHub graphs only show GitHub users, and that's never guaranteed to be a complete list.

Right; that settles it. We can go back to the original report then, i.e. how to automate updating the file in Sizzle.

**Comment by arthurvr** [comment]
> We can go back to the original topic then, i.e. how to automate updating the file in Sizzle.

As [seen in jQuery UI](https://github.com/jquery/jquery-ui/blob/master/Gruntfile.js#L338) is probably the easiest way. Just to run that before releases.

**Comment by arschmitz** [comment]
@arthurvr Just for reference a little simpler version with out the prior authors since thats not needed here https://github.com/jquery/css-chassis/blob/master/Gruntfile.js#L19

**Comment by mzgol** [comment]
@arthurvr 
> As [seen in jQuery UI](https://github.com/jquery/jquery-ui/blob/master/Gruntfile.js#L338) is probably the easiest way. Just to run that before releases.

This is a big *just*. I'd like to have it automated so that we don't forget about it. What's the current release process for Sizzle, @timmywil @gibson042? Just tag & publish manually or do we have anything automatic?

**Comment by arthurvr** [comment]
@arschmitz Of course.

---------------

> This is a big just. I'd like to have it automated so that we don't forget about it. What's the current release process for Sizzle, @timmywil @gibson042? Just tag & publish manually or do we have anything automatic?

Agreed on that, if we have an automated system for releases, it must be integrated in there.

---------------

Only thing is that we will have the same nearly the same piece of code written in 3 repos (or more) then. Nearly exactly the same task exists in [Chassis](https://github.com/jquery/css-chassis/blob/b4e714b3de6493d9916d17e946f7d0dc8c0373f9/Gruntfile.js#L19) and [UI](https://github.com/jquery/css-chassis/blob/master/Gruntfile.js#L19).

**Comment by dmethvin** [comment]
I'm not sure it can be blindly automated though. It seems that every jQuery Core release there are [commits that make it through with a changed or bad name/email](https://github.com/jquery/jquery/commit/03557db96c5b9fad22320e94b52b118c89f7b6f9), and may require `.mailmap` entries to clean them up. There's a step in the jquery-release script to do a really basic check that the last new name in the log is correct, but usually it requires a manual scan to be sure everything is okay. Perhaps the CLA scan will help us find these before they land?

**Comment by scottgonzalez** [comment]
> Perhaps the CLA scan will help us find these before they land?

The CLA check should catch all the common mistakes.

**Comment by gibson042** [comment]
I've usually released with manual tagging & publishing, but this is the perfect opportunity to automate. PR welcome, @arthurvr.

**Comment by arthurvr** [comment]
I don't really know what you guys mean with "the CLA check", and don't know how to integrate it. Somebody else may take it.

**Comment by mgol** [comment]
We're using jquery-release now so this is no longer an issue.
