### ISSUE TITLE
Sizzle.attr assumes passes element supports getAttribute

### ISSUE THREAD

**Issue by ayush** [jquery/sizzle#309]
Inside `Sizzle.attr` [there is an assumption](https://github.com/jquery/sizzle/blob/master/src/sizzle.js#L894) that the passed `elem` supports `getAttributes`. This isn't always true. As an example, the Comment element does not support this method. 

This leads to errors such as those reported [here](http://stackoverflow.com/questions/27408501/ng-repeat-sorting-is-throwing-an-exception-in-jquery) or [here](http://stackoverflow.com/questions/26808658/backbone-view-jquery-sizzle-error) 

The fix is to check if `elem` supports `getAttribute`. A condition like `elem.getAttribute !== undefined` should do the trick.

**Comment by ayush** [comment]
@gibson042 Sure, it may be intended to be called with element nodes. But Sizzle being used by jQuery makes Sizzle so pervasive that its inevitable that it will be used in unpredictable ways. So, Sizzle ought to safeguard itself against such uses instead of throwing an error. 

In this case, a simple things like looping over the children of a node and passing them via Sizzle could lead to errors if even one of the children is a non element node.

Given that, checks for non-element safety seem essential. If it is not desirable to fix it only in this spot, is there an issue open for treating this as a comprehensive fix?

**Comment by dmethvin** [comment]
> makes Sizzle so pervasive that its inevitable that it will be used in unpredictable ways

Can you provide a test case showing what you mean?

Is the right thing to do here to silently fail when the caller asks for attributes on something that can't hold attributes? I understand that it works for this particular use case, but silently ignoring invalid actions can make it very difficult to debug things in general.

**Comment by gibson042** [comment]
> So, Sizzle ought to safeguard itself against such uses instead of throwing an error.

I've been on the fence here for a while, which is why we don't have an open issue (but see #256 for clues). As @dmethvin alludes to, there's a strong argument that throwing such errors _is_ safeguarding against misuse.

> In this case, a simple things like looping over the children of a node and passing them via Sizzle could lead to errors if even one of the children is a non element node.

That case is **certainly** not supported. jQuery `.children()`/`.siblings()`/`.trigger()`/`.attr()`/`.val()`/etc. all filter out text and comment nodes, as does Sizzle itself.

**Comment by ayush** [comment]
@dmethvin / @gibson042  These are all great points. After reading them and thinking about it some more... I'm not sure myself :)

I'll try to reproduce this in a sandbox and write back if I have more intelligible things to say. Thanks much!

**Comment by mmahalwy** [comment]
@ayush any update on this?

**Comment by znck** [comment]
`elem.getAttribute is not a function` using jQuery with bootstrap and vuejs + vuerouter.
```
// Values
name = 'data-dismiss'
elem.docType = 11
elem.docName = '#document-fragment'
elem.firstChild = '<!--v-start-->'
// In call stack, jQuery.event.handlers has sel = '[data-dismiss="alert"]'
```

I don't know how to reproduce it but the error is there every time I click a link.

**Comment by gibson042** [comment]
Ah, that makes this a duplicate of https://github.com/jquery/jquery/issues/2055 (already fixed in jQuery master and soon to be released).

**Comment by znck** [comment]
@gibson042 Thanks :+1:
