### ISSUE TITLE
Expose Sizzle.expando so jQuery can clear it for IE8 cloning

### ISSUE THREAD

**Issue by dmethvin** [jquery/sizzle#310]
Per discussion in https://github.com/jquery/jquery/issues/1709 and https://github.com/jquery/jquery/pull/1652 .

**Comment by gibson042** [comment]
Note to self for further exploration: keying Sizzle expando caches on `elem.uniqueID` could provide universal oldIE clone-safety.

**Comment by markelog** [comment]
@gibson042 are we ready to release 2.1.2?

**Comment by gibson042** [comment]
I'd like to resolve #315, #316, and #311 before releasing, especially since f0a3bf6e necessitates a minor version bump (2.2.0).

**Comment by markelog** [comment]
> especially since f0a3bf6 necessitates a minor version bump (2.2.0).

Well, i guess you can call it new feature :-).
