### ISSUE TITLE
Sizzle.matches passes null context, causes document to be set to global document

### ISSUE THREAD

**Issue by catrope** [jquery/sizzle#311]
Related to #292 

If you call, say, `$foo.children( 'a' )` , checking which children of `$foo` match the `'a'` selector is done by `jQuery.filter`. If `$foo` has exactly one child, `jQuery.filter` will call `Sizzle.matchesSelector` which invokes `setDocument( elem.ownerDocument )` if necessary, and then passes that document to the `Sizzle` constructor.

However, if the number of children of `$foo` isn't exactly one, `jQuery.filter` will call `Sizzle.matches` instead, which just calls the `Sizzle` constructor directly, passing in `null` for the context, causing an invocation of `setDocument( window.document )` regardless of what document `$foo` is really in.

This means that the following code causes the document context to thrash: `setDocument` is invoked from every `.children()` call, which is detrimental to performance, since `setDocument` contains 300+ lines of feature/bug detection code.

```
var doc = document.implementation.createHTMLDocument( '' ),
    $foo = $( '<p><b>Hi</b></p>', doc ),
    $bar = $( '<p><b>Hello</b><i>world</i></p>', doc ),
    $baz = $( '<p>', doc );

// Context is doc due to $( '....', doc ) above
$baz.children( 'b' ); // Sets context to window.document
$foo.children( 'b' ); // Sets context to doc
$bar.children( 'b' ); // Sets context to window.document
$foo.children( 'i' ); // Sets context to doc
$bar.children( 'i' ); // Sets context to window.document
```

**Comment by timmywil** [comment]
Thanks for opening an issue. We actually had a discussion about this recently and meant to open one.

**Comment by catrope** [comment]
Yeah, one of my coworkers started that discussion, but I was the one writing our workarounds for it and I needed a URL to use to refer to this problem in my commit messages :)

I've also noticed anecdotally that if you do something like `$foo.find( 'a' ).filter( '[href]' )` where `$foo` is in a foreign document, two context switches occur for every call. That's probably the same underlying issue as this one, since `.filter()` calls the same Sizzle internals as `.children()`

**Comment by timmywil** [comment]
Implementation discussion [here](http://irc.jquery.org/%23jquery-dev/default_%23jquery-dev_20150126.log.html#t10:51:30). @gibson042 or I will get to it as soon as one of us is free.
