### ISSUE TITLE
Consider renaming shadowed document variable

### ISSUE THREAD

**Issue by catrope** [jquery/sizzle#312]
Figuring out what this code does was a fun exercise:

```
if ( ( context ? context.ownerDocument || context : preferredDoc ) !== document ) {
```

It turns out that `document` is **not** the global document (`window.document`), instead it's a local variable that contains the most recently used document (set by `setDocument()`). My IDE helps confuse me by highlighting `document` in a special color. But there *is* a variable for the global document and it is in this expression, it's called `preferredDoc`.

Using shadowing to create a local variable called `document` that sometimes is and sometimes isn't equal to the global variable called `document`, and then creating a different local variable (`preferredDoc`) that is always equal to the global variable called `document` is terribly confusing. Reading a line of code like the one I quoted in isolation gives the impression that it does the opposite of what it actually does.

**Comment by timmywil** [comment]
It used to be named `doc` in setDocument, but a problem arose where maintainers – myself included – would sometimes accidentally use the global document. We shadow purposefully to avoid that. I realize it is confusing to read, but I'd rather us err on the side of using the local document variable.
