### ISSUE TITLE
Browserstack and android devices

### ISSUE THREAD

**Issue by markelog** [jquery/sizzle#314]
Currently build fails on all android devices, see more info in travis builds - https://travis-ci.org/jquery/sizzle/builds

Browsertack is notified.

I purpose to temporary disable to run tests on them until browserstack figure out the problem.

/cc @mzgol

**Comment by mzgol** [comment]
+1. Builds always failing start getting ignored which is bad.

**Comment by markelog** [comment]
Temporary disabled test execution on android devices, i think this issue should remain open until testing on those will be resurrected

**Comment by mzgol** [comment]
I've emailed BrowserStack again; we shouldn't have to disable testing on supported browsers for this long.

**Comment by markelog** [comment]
Need to be better next time, although it is pretty understandable, we don't have a lot resources for such tasks

**Comment by gibson042** [comment]
Fixed by 85123dbb1b84c7d1b1612d4b7cfe56310fe5e46b: https://travis-ci.org/jquery/sizzle/builds/109198885
