### ISSUE TITLE
Check existing selector cache and skip matchesSelector when possible

### ISSUE THREAD

**Issue by timmywil** [jquery/sizzle#315]
For context: https://github.com/jquery/jquery/issues/2042#issuecomment-72469549

This should improve performance of selector extensions when called multiple times. When making this change, let's record some performance metrics for the release notes!

**Comment by timmywil** [comment]
A massive improvement for the :visible selector.
![screenshot 2015-02-13 17 16 23](https://cloud.githubusercontent.com/assets/192451/6196182/151de090-b3a4-11e4-85fb-d922ca281ea8.png)

**Comment by dmethvin** [comment]
![whoa](https://cloud.githubusercontent.com/assets/157858/6196360/ce53f15c-b3a5-11e4-9b0e-f53ecc91cfa9.jpg)

**Comment by timmywil** [comment]
Granted, this is taking advantage of caching, so the first time you use the selector is the same, but each subsequent call is greatly improved.
