### ISSUE TITLE
Sizzle.matches not passing enough vars to condense function

### ISSUE THREAD

**Issue by mmclau14** [jquery/sizzle#318]
I used the sizzle library to filter a list of elements by :even. It looks like it did so correctly until it tried to condense the array that it had. Only one argument was passed when it needs at least 2.

EDIT:
the error occurs at this line in the condense function 
```javascript
map.push(i);
```

**Comment by gibson042** [comment]
Please create and link to a live test case demonstrating your expectations and our gaps in meeting them on a site like http://jsfiddle.net/ or http://jsbin.com/ so we can inspect what's actually happening.

**Comment by gibson042** [comment]
I'm closing for now, but will reopen if a test case is presented.
