### ISSUE TITLE
Class Selector in SVG Elements (IE)

### ISSUE THREAD

**Issue by ColinFrick** [jquery/sizzle#322]
After upgrading jQuery from version 1.11.0 to 1.11.2 class selectors in SVG elements are not working anymore. That's because before the commit 08cb4519b079af502e0441857bc3c01d31030545 it was checked if getElementsByClassname is available on the element (context). In Internet Explorer getElementsByClassName is available on the document, but not on SVG Elements.

So following test would fail with "Object doesn't support property or method getElementsByClassName"
```javascript
	div = jQuery("<svg width='200' height='250' version='1.1' xmlns='http://www.w3.org/2000/svg'><rect x='10' y='10' width='30' height='30' class='foo'></rect></svg>")[0];
	equal( Sizzle(".foo", div).length, 1, "Class selector against SVG" );
```

Any way I could work around this problem?

**Comment by gibson042** [comment]
I'll make sure this is fixed (basically, restoring the `context.getElementsByClassName` checks removed by 08cb4519b079af502e0441857bc3c01d31030545) in the next release, which will appear in jQuery 3.0. It would be helpful if you could put a test case together and/or document a range of affected browsers and/or submit a pull request.

In the meantime, you can work around the issue by using [`[class~=foo]` selectors](http://www.w3.org/TR/css3-selectors/#attribute-representation) instead of the [`.foo` shorthand](http://www.w3.org/TR/css3-selectors/#class-html).

**Comment by markelog** [comment]
What about won't fix clause - https://contribute.jquery.org/wont-fix/

> jQuery is primarily a library for the HTML DOM, so most problems related to SVG/VML documents or namespaced elements are out of scope. We do try to address problems that "bleed through" to HTML documents, such as events that bubble out of SVG.

**Comment by timmywil** [comment]
We'll provide SVG fixes sometimes if they're short and the cost to benefit ratio is high. That said, the wontfix clause is still valid because jQuery will not become an SVG library.

**Comment by gibson042** [comment]
https://github.com/jquery/jquery/issues/2199#issuecomment-93599286

We don't promise full support, but we don't reject anything matching /svg/i out of hand anymore either.

**Comment by markelog** [comment]
> We'll provide SVG fixes sometimes if they're short and the cost to benefit ratio is low.

I think we should document exactly that, since now we saying - 

> so most problems related to SVG/VML documents or namespaced elements are out of scope

As far as i recall, none of recent tickets about "/svg/i" were rejected, so we, at least should remove the phrase "most" from there.

**Comment by timmywil** [comment]
I disagree. There's a vast multitude of things related to SVG that we don't support that far outnumber the things that we have accepted. I think the clause is fine as it is. We'd rather give the impression that we *will* reject most issues.

**Comment by jcward** [comment]
FYI, if upgrading jQuery isn't an option for you, there's a polyfill for `SVGElement` here: https://github.com/clientIO/joint/issues/117#issuecomment-194699222

*Reproduced here for convenience:*

```
if (SVGElement.prototype.contains === undefined) {
    SVGElement.prototype.contains = function(el) {
        return $.contains(this, el);
    };
}

if (SVGElement.prototype.getElementsByClassName === undefined) {
    SVGElement.prototype.getElementsByClassName = function(className) {
        return this.querySelectorAll('.' + className);
    };
}
```

Sorry to bump this old issue. Carry on.
