### ISSUE TITLE
ID selectors provide no filtering benefit at all in oldIE

### ISSUE THREAD

**Issue by gibson042** [jquery/sizzle#333]
Ref jquery/jquery#2231

`getElementById` might be unreliable in those clients, but the results of any given call can be verified (as happens in the ID filter). We should perform such verification, perhaps by leveraging the filter, rather than [delete the `Expr.find` method entirely](https://github.com/jquery/sizzle/commit/516a8ad630655d2cd8c67bf75ac2550b640dd5ee#diff-7d34356c0b7229dd5da8b6c7711b32b7).

**Comment by timmywil** [comment]
:+1:
