### ISSUE TITLE
uniqueSort is slow for arrays with length > 500

### ISSUE THREAD

**Issue by AgCouper** [jquery/sizzle#342]
This is especially evident on Chrome. I discovered this issue while investigating a leak in our internal app. The leak didn't consume much memory, but it slowed the app to the crawl after just a few minutes of using it. Profiling showed that the app spent more than 85% of the non-idle execution time in `Sizzle.uniqueSort`, sorting a number of arrays with length around 500 elements.
And the slowest part of uniqueSort implementation is the call to `results.sort(sortOrder)`. My measurements show that this is because of the `sortOrder` comparator, which prevents browsers from sorting the array real fast: `results.sort()` is much faster than `results.sort(sortOrder)`.
I don't know all the intricate details about uniqueSort, but can we just sort results array with `results.sort()` and then do a pass over the sorted array to detect duplicate elements, like this: 
```javascript
	results.sort();

	var i = 0;
	for (i = 1; i < results.length; ++i) {
		if (results[i-1] === results[i]) {
			hasDuplicate = true;
			break;
		}
	}
```
It really speeds the things up.

**Comment by gibson042** [comment]
`uniqueSort` sorts elements into document order, which requires an [explicit comparator](https://github.com/jquery/sizzle/blob/a7020477b0433ac08d66baf9eebb3f9d24868e21/src/sizzle.js#L759). However, there's only one call to `uniqueSort` [in Sizzle](https://github.com/jquery/sizzle/blob/a7020477b0433ac08d66baf9eebb3f9d24868e21/src/sizzle.js#L1941), and only a handful in jQuery (`.find`, `.closest`, `.add`)—all of which are conditional or otherwise avoidable. I recommend tweaking your code to avoid the automatic sorting.

**Comment by seyfer** [comment]
@gibson042 I find this issue still relevant. See 2 connected tickets.
The problem is that Sizzle used in other libraries on the background and brings the same problem to these libraries.

**Comment by gibson042** [comment]
As I explained above, `uniqueSort` does more than just remove duplicate elements—it sorts a collection into DOM order, which cannot be done by an argument-free `.sort()`. @seyfer that call to `uniqueSort` is specific to use of multiple positional matchers like `:first`, `:last`, `:even`, `:odd`, `:eq(N)`, `:lt(N)`, and `:gt(N)`, all of which are ill-advised and deprecated. I recommend rewriting the logic to avoid using those nonstandard selectors, or at the very least to using no more than one at a time, in which case the slow sorting will no longer be necessary.

**Comment by seyfer** [comment]
@gibson042 I'm not a `tablesaw` maintainer, we use it in our project, but I do not know how to fix it for them.

Is it possible that somebody from Sizzle team could create a PR into `tablesaw` with fix?
