### ISSUE TITLE
Make sure all browser globals are taken from window

### ISSUE THREAD

**Issue by mzgol** [jquery/sizzle#345]
jQuery now doesn't assume the browser environment by declaring globals explictely in [its .jshintrc](https://github.com/jquery/jquery/commit/76df9e4e389d80bff410a9e5f08b848de1d21a2f#diff-b7ac5ae82f282a9e6768c835add5edfd) instead of just using `"browser": true`. Such a change is not present in [Sizzle's src/.jshintrc](https://github.com/jquery/sizzle/blob/a6ca3e9919c7a77001bdec01b3579e4bafd73a84/src/.jshintrc#L19) and it should.

Refs https://github.com/jquery/sizzle/issues/343#issuecomment-131456577

**Comment by gibson042** [comment]
I'm in favor. @mzgol, would you like to PR?

**Comment by mzgol** [comment]
Yup, already assigned to myself. :)

**Comment by mzgol** [comment]
PR: #351
