### ISSUE TITLE
Question of addHandle

### ISSUE THREAD

**Issue by lovekonakona** [jquery/sizzle#353]
```javascript
/**
 * Adds the same handler for all of the specified attrs
 * @param {String} attrs Pipe-separated list of attributes
 * @param {Function} handler The method that will be applied
 */
function addHandle( attrs, handler ) {
	var arr = attrs.split("|"),
		i = attrs.length;

	while ( i-- ) {
		Expr.attrHandle[ arr[i] ] = handler;
	}
}
```

`i = attrs.length;`

Is there use `attrs` right? Not use `attr`?

**Comment by mzgol** [comment]
I don't understand the question. There is no `attr` in the code, only `attrs`. What is the issue?

(it doesn't look like there's any bug being reported here so I'll close this one)

**Comment by lovekonakona** [comment]
Sorry, I think the right code is `i = arr.length;`

**Comment by dmethvin** [comment]
That sure does look wrong!

**Comment by mzgol** [comment]
@lovekonakona Ah, ok, now I see what you mean, thanks for the report!

@dmethvin I guess it didn't cause any observable bugs since the string length is generally larger than the split one so the function just sets a value on the `undefined` several times?

**Comment by timmywil** [comment]
@mzgol That'd be my guess too. I'll do a fix real quick.

**Comment by dmethvin** [comment]
:+1: to you @lovekonakona, I guess it really is true that with enough eyes all bugs are shallow!
