### ISSUE TITLE
Replace ID-attribute selectors with ID-selectors where possible

### ISSUE THREAD

**Issue by gibson042** [jquery/sizzle#354]
We handle element-context qSA by [prefixing `[id='…'] `](https://github.com/jquery/sizzle/blob/51f87d087ac68f897c56fe5229f56105b36ba5d0/src/sizzle.js#L296) to selectors. However, the queries would exhibit better performance if we used instead used `#… ` where available (e.g., in HTML and SVG context).

**Comment by timmywil** [comment]
Sounds like a good idea. I guess we'd just check if the context element is XML?

**Comment by gibson042** [comment]
Yeah, that's the basic plan.
