### ISSUE TITLE
Error when testing on oldIE

### ISSUE THREAD

**Issue by gibson042** [jquery/sizzle#362]
The browsers never report back: https://travis-ci.org/jquery/sizzle/builds/89668704#L443

There are two causes:
* [`jsonp-polling`](https://github.com/jquery/sizzle/blob/46ab43bb569f6e0274c60e55664e91fb626e5570/Gruntfile.js#L203) is not a supported option for karma `transports`: https://karma-runner.github.io/0.13/config/configuration-file.html
* karma is currently broken on IE<8: https://github.com/karma-runner/karma/issues/1696

**Comment by mzgol** [comment]
Did you upgrade Karma to 0.13? I specifically avoided that because it breaks in old IE. Dowgrade to 0.12 and you should be fine. Edge will be recognized as Chrome but that's not terribly important.

**Comment by mzgol** [comment]
Yeah, I'd revert the Karma upgrade from 5a0dd09b7f7d9415213fb9b35fd0c565bcf602ff until oldIE issues are resolved.

**Comment by gibson042** [comment]
Good call. It is done in cfc50b37e81a3453c4f0a5d2eac3f98f9009ce1b, but I'll leave this open to track the upstream issues.
