### ISSUE TITLE
Some inconsistent whitespace styling

### ISSUE THREAD

**Issue by stevemao** [jquery/sizzle#373]
https://github.com/jquery/sizzle/blob/master/src/sizzle.js#L528
```js
subWindow.addEventListener( "unload", unloadHandler, false );
```

vs

https://github.com/jquery/sizzle/blob/master/src/sizzle.js#L544
```js
return !div.getAttribute("className");
```

Should there be a whitespace between `(` and `"`?

**Comment by gibson042** [comment]
There should be, but [I've been holding off on major whitespace changes](https://github.com/jquery/sizzle/pull/330/files#r27985694) until the [parenthesized expression exception](https://github.com/jscs-dev/node-jscs/pull/1777#issuecomment-139520076) is [restored](https://github.com/jquery/jquery/pull/2542#discussion_r37199334).

**Comment by stevemao** [comment]
Oh cool. Sorry didn't see the PR.

**Comment by markelog** [comment]
@gibson042 Maybe you can start a discussion about that at https://github.com/jquery/contribute.jquery.org otherwise it might be awhile before code would look consistent.
