### ISSUE TITLE
Travis has been broken for a long time

### ISSUE THREAD

**Issue by mgol** [jquery/sizzle#377]
Travis tests have been broken for over 4 months: https://travis-ci.org/jquery/sizzle/builds. That's bad, especially that new commits have been landing since and we can't know if they didn't introduce regressions.

**Comment by gibson042** [comment]
It's true, partly because of #362 and partly from the cross-window `Sizzle.noConflict()` testing (addressed by 087ba11b104dfe66ac82523246899381b7a637d3) that I didn't notice through the noise of the former. I have been confirming fixes manually, and we all know how that goes.

Ideas and PRs welcome.

**Comment by mgol** [comment]
We reverted Karma to 0.12 so #362 shouldn't be an issue. We have timeouts in other browsers, updating `karma-browserstack-launcher` to the newest release might fix this problem; I wanted to do that & check but then I hit this `noConflict` issue. Perhaps we can re-try that (unless the newest `karma-browserstack-launcher` requires Karma 0.13 to run but it doesn't seem to be the case).

**Comment by gibson042** [comment]
@mgol I've done what I can, and we're back to timeouts galore: https://travis-ci.org/jquery/sizzle/builds/108436309

Upgrading karma may help things, and v0.13.19 [includes a `socket.io-client` that works with IE<8](https://github.com/karma-runner/karma/commit/67828aa45e4686698e4b0f4a3f0771f3e3933e25), but I guess we're still waiting for [`forceJSONP`](https://github.com/karma-runner/karma/pull/1818).

**Comment by dignifiedquire** [comment]
I just released [`0.13.20`](https://github.com/karma-runner/karma/releases/tag/v0.13.20) which ships with `forceJSONP`

**Comment by gibson042** [comment]
Fixed by 85123dbb1b84c7d1b1612d4b7cfe56310fe5e46b: https://travis-ci.org/jquery/sizzle/builds/109198885

Thanks @dignifiedquire!
