### ISSUE TITLE
Create GitHub releases

### ISSUE THREAD

**Issue by gibson042** [jquery/sizzle#380]
...because tags aren't enough.

**Comment by solacortez** [comment]
1. Vhj @

**Comment by cgatian** [comment]
Randomly just passing by on this repo and saw this issue.  @gibson042  do you mind elaborating on what your talking about?  What are Github releases?

**Comment by mgol** [comment]
@cgatian https://github.com/jquery/sizzle/releases

**Comment by cgatian** [comment]
:thumbsup:

**Comment by mgol** [comment]
FWIW, we do have entries for newer releases now. But it's not likely we'll fill in the older ones. I think we can close this.
