### ISSUE TITLE
Explanation of why we support ancient browsers

### ISSUE THREAD

**Issue by markelog** [jquery/sizzle#389]
I think we should add it to the wiki. Also it would be good to decide in what browsers versions should we ask contributors to check their additions

**Comment by timmywil** [comment]
I'm not sure we need to explain it. If all goes according to @gibson042's plan, we will be retiring Sizzle.

**Comment by markelog** [comment]
That's what I want to document, as agreed on the meeting.

And also see note about contributors

Regards,
Oleg

**Comment by timmywil** [comment]
Ok, that wasn't what I took away from the meeting. Also, if it's retired, there won't be additions.

**Comment by markelog** [comment]
There is a lot of open questions on how this would actually work. We have a long way to go before we can retire anything 

Regards,
Oleg

**Comment by timmywil** [comment]
Fair enough.

**Comment by breck7** [comment]
Is this plan posted anywhere at all? Would be interested in learning more.

**Comment by markelog** [comment]
@breck7 nope, that's the point of this ticket

**Comment by mgol** [comment]
I have a WIP PR to remove Sizzle (dropping custom traversal logic together with removing positional selectors will happen separately) in https://github.com/jquery/jquery/pull/4395, I don't think at this point we need any justification for Sizzle browser support, especially after so many years.
