### ISSUE TITLE
Selectors with escaped = characters gaining extra single-quotes through filter().

### ISSUE THREAD

**Issue by obermillerk** [jquery/sizzle#408]
EDIT: using jQuery version 3.2.1

When using a selector like `"#\\=\\]"` (which is intended to find an element with the id `=]`) in the filter function, the = is not recognized as being escaped.  I've tracked this down to [a specific line](https://github.com/jquery/sizzle/blob/master/src/sizzle.js#L987) where single quotes are inserted after an equals character when it is eventually followed by a closing square bracket (which also is not recognized as being escaped).  The [rattributesQuotes](https://github.com/jquery/sizzle/blob/master/src/sizzle.js#L106) regex here does not seem to check that the = isn't escaped, so even if there is an escaped equals character (which gets escaped by the jQuery.escapeSelector() function so I assume this is not intended) it is thought to be an attribute selector.

This can be very simply isolated.  All it takes is `$('body').filter("#\\=\\]")`, in a JS file for a basic html page with jQuery.  You could even replace `"#\\=\\]"` with `"#" + $.escapeSelector("=]")` and this will still happen as it results in the same string.

**Comment by gibson042** [comment]
Works for me: https://jsfiddle.net/v8xbtyrj/

**Comment by obermillerk** [comment]
Instead of using a premade jquery object as the selector for the filter using a string creates this error. [https://jsfiddle.net/gajm29fg/3/](https://jsfiddle.net/gajm29fg/3/) You can see the error output in the browser console on this fiddle.

**Comment by staabm** [comment]
@obermillerk your example also doesnt work for simple id-selectors without css meta characters:

https://jsfiddle.net/gajm29fg/4/

**Comment by obermillerk** [comment]
@staabm this is because the selector is only selecting the ul element.  [Here](https://jsfiddle.net/gajm29fg/5/) it works, but there is still an error being produced in my first example [https://jsfiddle.net/gajm29fg/3/](https://jsfiddle.net/gajm29fg/3/) that should be resolved because it's showing up in my electron program when it shouldn't be.

**Comment by obermillerk** [comment]
@gibson042 can this be re-opened please? It is definitely a bug that needs to be fixed.

**Comment by gibson042** [comment]
Confirmed, this is indeed an issue with `Sizzle.matchesSelector`.
