### ISSUE TITLE
at the sizzle's home page.!!! page's content is wrong??

### ISSUE THREAD

**Issue by lfzy** [jquery/sizzle#410]
**The page content and source code do not match**

at the 
>Sizzle.selectors.setFilters.LOWERCASE_NAME = function( elements, argument, not ) {}

It is easy to extend Sizzle -- even Sizzle's POS selectors. For example, to rename :first as :uno:
```
Sizzle.selectors.match.POS = new RegExp( oldPOS.source.replace("first", "uno"), "gi" );
Sizzle.selectors.setFilters.uno = Sizzle.selectors.setFilters.first;
delete Sizzle.selectors.setFilters.first;
Sizzle("div:uno"); // ==> [ <div> ]
```

**where  is  POS at the sizzle's code ?**
in the old version , i  can't find 'POS' !!
I had searched on Google, but get nothing.

**Comment by lfzy** [comment]
@timmywil    tks!!!!

**Comment by Krinkle** [comment]
(This seems to be about <https://github.com/jquery/sizzle/wiki>, not <http://sizzlejs.com>.)

**Comment by lfzy** [comment]
Yes!!   You are right!   
How should I do this...?! @Krinkle  
Thank you very much!

**Comment by mgol** [comment]
We're going to retire Sizzle soon so it doesn't seem worth it to focus on such details anymore.
