### ISSUE TITLE
NPM install issue using new version of Node.js

### ISSUE THREAD

**Issue by pengbomuzzy** [jquery/sizzle#412]
When using Node.js 8.9.0 LTS with Windows 10, after using "npm install" to get modules for sizzle, it runs forever and there is no indication of the installing status/progress.

My solution is downgrading to a lower version of Node.js (actually it is npm package that matters), I choose Node.js 8.1.0 (npm - 5.0.3) which makes installling progress go completely with no issue.

**Comment by JuanMaRuiz** [comment]
Hi @pengbomuzzy  I have checked on my machine (macOs) using the same node version as you and everything seems to be working fine.

**Comment by timmywil** [comment]
I had forgotten about this issue. Something like this is unlikely to be an issue with Sizzle itself.
