### ISSUE TITLE
Help needed: Import sizzle into Vue-Cli 3

### ISSUE THREAD

**Issue by katerlouis** [jquery/sizzle#425]
It's crazy– 
I just can't get Sizzle to work in my vue-cli 3 setup.

And I don't find on the internet how to do so– Apologies if this is such a trivial thing to ask.

I successfully installed Sizzle as a dependency vue-cli project like so:
```bash
npm install sizzle -S
```

and my package.json correctly reflects that.
![image](https://user-images.githubusercontent.com/1983382/44005629-a27d7c3c-9e76-11e8-9235-75d3378539cb.png)

Where 
```js
import $ from "jquery"
```
works in my `App.vue`, I can't get a similar thing to work with Sizzle–

Could you please help me?

**Comment by mgol** [comment]
The import works fine for me on codesandbox.io: https://codesandbox.io/s/zkk7jvx2lx (open the DevTools console and you'll see Sizzle logged). Hence, it looks like some configuration problem on your side.
