### ISSUE TITLE
Any chance to get jQuery functions .find(), .filter(), .add(), .not() aswell?

### ISSUE THREAD

**Issue by katerlouis** [jquery/sizzle#443]
I don't want to bloat my application with jQuery, but heavily rely .find() and maybe sometimes .filter(), .add(), and .not() – 

Is there a way to get this functionality for sizzle?

**Comment by mgol** [comment]
You can use our AMD modules or compile a custom jQuery version without modules you don't need:
https://github.com/jquery/jquery#modules

Sizzle is on its way to be end-of-lifed once we migrate jQuery to an alternative smaller selector solution so no drastic changes in Sizzle are planned.

**Comment by katerlouis** [comment]
What do you mean with `on its way to be end-of-lifed`?

**Comment by mgol** [comment]
See https://github.com/jquery/sizzle/issues/293#issuecomment-154581860

The plan is to have jQuery 4 no longer rely on Sizzle. When & if that happens, Sizzle will become an archived project.
