### ISSUE TITLE
home page of sizle: documentation link is broken

### ISSUE THREAD

**Issue by cekvenich** [jquery/sizzle#447]
https://wiki.github.com/jquery/sizzle

It says bad browser request.

**Comment by gibson042** [comment]
Hmm, I'm not sure where the source of that page is located. Can anyone else in @jquery/core help?

**Comment by mgol** [comment]
I haven’t heard about this domain before but this behavior is not related to Sizzle, https://wiki.github.com/ behaves in the same way. Closing.

@cekvenich Where did you get this URL from?

**Comment by cekvenich** [comment]
This should not be closed. 
On https://sizzlejs.com the documentation link is not working! Please reopen.

**Comment by timmywil** [comment]
That is the original site for Sizzle and was created by the jQuery team years ago. But I don't know where the source lives. It could honestly be ftp'd to some www folder. However, I don't think anyone is being led astray by that broken link. If you try to find Sizzle, you'll be led here.

**Comment by cekvenich** [comment]
You are lead to the home page, and the first thing one would click is documentation - that is the broken link we are talking about. Seem like you should be able to get a handle to the DNS from the jquery team - now that their blog has said they will remove sizzle from jquery 4.0.

**Comment by timmywil** [comment]
I'd be happy to fix the link, but someone more familiar with that website will need to help out (maybe @scottgonzalez or @gnarf?).

**Comment by timmywil** [comment]
By the way, you're talking to the jQuery team. The site is old enough that it predates all of us.

**Comment by mgol** [comment]
Reopening since we now have an issue to resolve: fixing the link on the home page.

**Comment by mgol** [comment]
@gibson042 @timmywil BTW, the page is so old I think it'd be better to just redirect it to https://github.com/jquery/sizzle/wiki, removing the reference to the home page from that wiki. Maybe the discussion group should be archived as well, there hasn't been any posts there for more than 8 years.

**Comment by timmywil** [comment]
Yea, we should remove the link to the google group.

**Comment by timmywil** [comment]
Pinging more cool people @dmethvin @jquery/infrastructure @jquery/core-admin

**Comment by jorydotcom** [comment]
I think it's on a digital ocean droplet (simple-sites.ops.jquery.net) - no telling what the password is on that thing though

**Comment by dmethvin** [comment]
Do we want to maintain that site? If not, we could just redirect the DNS to the Wiki and not try to track it down.

**Comment by mgol** [comment]
@dmethvin I proposed exactly that in my comment above. :)

**Comment by NReilingh** [comment]
Some additional context: people can be led to htps://sizzlejs.com because it is linked from a few different places on https://jquery.com, like the icon in the top header bar.

**Comment by mgol** [comment]
@NReilingh Good point. Since we plan to retire Sizzle soon, perhaps we should remove that link from the jQuery site.

**Comment by timmywil** [comment]
We still want to fix the DNS.

**Comment by Mapiac** [comment]
Curious @Mgol anywhere to follow along where v.4 is at timeline wise (removal of Sizzle)? Tnx

**Comment by mgol** [comment]
@Mapiac No specific timeline but I have a WIP PR (https://github.com/jquery/jquery/pull/4395) that first inlines Sizzle in jQuery & then removes all obsolete workarounds etc. This will be the first step, later on we'll simplify the code further, removing manual traversal code. But after the mentioned PR runs all the code used in jQuery will be directly in the jQuery repository; code from this Sizzle repo will only be used on the [`3.4-stable` branch](https://github.com/jquery/jquery/tree/3.4-stable).

**Comment by mgol** [comment]
I've just merged another PR that ports most Sizzle tests to jQuery so that we don't miss anything when doing the refactor: https://github.com/jquery/jquery/pull/4406.

**Comment by khode-mohsen** [comment]
use this https://github.com/jquery/sizzle/wiki

**Comment by timmywil** [comment]
The redirect is in place!

sizzlejs.com
