### ISSUE TITLE
cannot find elements with ids that have special characters like /, .

### ISSUE THREAD

**Issue by sainthkh** [jquery/sizzle#465]
Test Code:

```html
<html>
<head>
<script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
</head>
<body>
<div id="hello.world">id with dot</div>
<div id="hello/world">id with slash</div>
<div class="hello/world/2">class with slash</div>

<script>
  $('#hello.world').css('color', 'red') // cannot find an element
  console.log(document.getElementById('hello.world'))

  // $('#hello/world').css('color', 'red') // throws an error
  console.log(document.getElementById('hello/world'))

  $('.hello/world/2').css('color', 'red')
</script>
</body>
</html>
```

When you make an element with an id like "hello/world", Sizzle fails to find it and throws an error. 

If it has '.' in the middle of a string, it cannot find an element. 

These are all valid id names [according to the spec](https://www.w3.org/TR/html50/dom.html#the-id-attribute).

**Comment by mgol** [comment]
You need to escape an ID when used in a selector via `Sizzle.escape` which is based on the standard `CSS.escape` method. See https://github.com/jquery/sizzle/issues/363
