### ISSUE TITLE
Why is sizzle loading a script from massehight.com ?

### ISSUE THREAD

**Issue by dimerman** [jquery/sizzle#470]
While developing I caught this fragment of network traffic.
I couldn't find any information about the host `massehight.com` but looks like it's publishing metrics of some sort.
I had a brief look at sizzle's code but couldn't find any reference to this.
Am I misreading things?

![Screen Shot 2020-04-26 at 10 31 03 AM](https://user-images.githubusercontent.com/633961/80314952-8e02ea80-87a9-11ea-994b-c062f8280787.png)

**Comment by dmethvin** [comment]
There's no information in the report so it's not a bug. A screen shot of a devtools panel does not tell us the version of Sizzle, where the script came from, what code it was called from, or other important things. You can put a breakpoint on the call to determine more.

**Comment by dimerman** [comment]
@dmethvin maybe this helps:
```
/*!
 * Sizzle CSS Selector Engine v1.1.2
 * https://sizzlejs.com/
 *
 * Copyright JS Foundation and other contributors
 * Released under the MIT license
 * https://js.foundation/
 */
```
I'm having difficulty tracing what is loading sizzle itself: if it's a browser plugin I could use some help identifying it. thanks!

**Comment by dimerman** [comment]
Turns out the chrome extension "Ultra Ad Block" was responsible for this.
I see the version of sizzle used is not even supported.
My concern was a malicious pull request that would have compromised the library.
cheers.
