### ISSUE TITLE
Don't set attributes while querying

### ISSUE THREAD

**Issue by fregante** [jquery/sizzle#483]
While using Sizzle in a `MutationObserver` that watches for attributes, I found that it's changing attributes in my DOM during an operation that I expect to be "pure", and it's causing a loop. 

https://github.com/jquery/sizzle/blob/20390f05731af380833b5aa805db97de0b91268a/src/sizzle.js#L336-L346

Why is this necessary? Should the condition be changed to only happen in browsers that don't support `:scope`?

**Comment by mgol** [comment]
`:scope` can only be used if the context to run `querySelectorAll` is maintained. This is not the case for selectors starting with the sibling combinator - we need to query on the parent so we can’t rely on `:scope` there.

**Comment by fregante** [comment]
So why is Sizzle still making the change even for selectors that don't need that? 

What I'm asking is to avoid doing this unless strictly necessary, which feels like it's not for the vast majority of selections.

**Comment by mgol** [comment]
Other selectors shouldn’t be doing that. If you have an example where that’s not the case, please submit a test case on a service like JS Bin using jQuery or Sizzle and we’ll reopen the issue.
