### ISSUE TITLE
Deprecated `unload` event handler used in `Sizzle.setDocument`

### ISSUE THREAD

**Issue by westonruter** [jquery/sizzle#498]
In `Sizzle.setDocument` there is the following code:

https://github.com/jquery/sizzle/blob/4194dc464e7381139220e39ceb46c0bdfe12dd59/src/sizzle.js#L624-L641

MDN warns against using the `unload` event: https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event#usage_notes

Chrome is deprecating the `unload` event: https://developer.chrome.com/blog/deprecating-unload/

Using `unload` hurts performance because it disables bfcache.

For these reasons, since this code is specifically for Internet Explorer (and likely not Edge), should some `User-Agent` sniffing be done to prevent it from running on modern browsers?

**Comment by westonruter** [comment]
Ah, I see from https://github.com/jquery/sizzle/issues/495#issuecomment-1430506064 that Sizzle is deprecated and will be archived. So I guess the answer is no.

**Comment by mgol** [comment]
Yes, Sizzle is going to get archived soon and we don't plan further changes to the library.

If you cared about Sizzle because of jQuery, though, this issue has been fixed in jQuery `3.7.1` by limiting the handler attachment to just IE & Edge Legacy in https://github.com/jquery/jquery/issues/5281.
